### ISSUE TITLE
Socket filename

### ISSUE THREAD

**Issue by jimbobmcgee** [rhandom/perl-net-server#18]
How is one supposed to get the filename back from a socket?

I'm stuck with a vendor_perl version of `Net::Server::Proto::UNIX`, which is at v2.007, and neither `NS_port` or `NS_unix_path` return anything...

**Edit**: In the light of *not* coming off the back of a 17-hour shift trying to fix something in a downstream system, I appreciate that this might have come across a bit abrupt, for which I apologise.  In any case, my question still stands.  

I'm looking at a downstream Perl script which seems to have *tried* to account for v2.0, by doing `my $file = Net::Server->VERSION >= 2 ? $sock->NS_port : $sock->NS_unix_path`, but both are coming up empty.

All documentation/fora I have read so far suggests that `NS_port` was chosen to replace `NS_unix_path` back at the turn of v2.0, and then `NS_unix_path` was put back in, circa v2.002 as a backwards-compatibility wrapper that simply returns `NS_port`.  Appreciating you're now up to v2.009 while vendor_perl is still at v2.007, but I'd have thought both should return *something*, given the changelog for v2+ doesn't address this situation directly.

I was hoping to shim in a quick fix to the downstream script, rather than mess with the vendor_perl implementation, but can't seem to work out an alternative means to either retrieving the real path from the blessed socket object, nor stashing the filename in the blessed socket object after the effect.

**Comment by rhandom** [comment]
I added a small modification to t/UNIX_test.t which I'll push up in a little bit.  The NS_port _should_ work as shown in the new test output.  If you're still not seeing it, there may be something else going on with your client connection.

prove -v -Ilib t/UNIX_test.t
t/UNIX_test.t ..
1..5
ok 1 - Can fork on this platform
ok 2 - Got needed ports (20803)
ok 3 - Pipe works
ok 4 - use Net::Server
# unix port - NS_port: /tmp/KEsH9hrtUj/socket
# tcp port - NS_port: 20803
ok 5 - Got the correct output from the server
ok
All tests successful.
