### ISSUE TITLE
The semaphore is not removed on server shutdown

### ISSUE THREAD

**Issue by targzeta** [rhandom/perl-net-server#30]
Hi,
this is my server file:
```
user  myusr
group myusr

serialize semaphore
```

When I start the server I can see:
```
ipcs -s

0x00000000 6717536    myusr      700        1
```
but the semaphore doesn't seems released when I stop the server. So, when I restart the server, the number of semaphores acquired increase.
```
ipcs -s

0x00000000 6717536    myusr      700        1
0x00000000 7077991    myusr      700        1
```

After a while that I restart my server I get this error:
`ERROR> 2022/05/09-12:19:39 Semaphore error [No space left on device]#012  at line 92 in file /usr/local/share/perl5/Net/Server/PreForkSimple.pm`

I guess you have to call `$s-remove()` to resolve this little issue.

Thank you in advance. Best regards,
Emanuele

**Comment by targzeta** [comment]
This little patch seems to work:
```diff
--- ./Server.pm.orig    2021-03-22 16:03:49.000000000 +0100
+++ ./Server.pm 2022-05-09 12:33:54.703894742 +0200
@@ -752,6 +752,9 @@
         && defined($prop->{'pid_file_unlink'})) {
         unlink($prop->{'pid_file'}) || $self->log(1, "Couldn't unlink \"$prop->{'pid_file'}\" [$!]");
     }
+    if (defined($prop->{'sem'})) {
+        $prop->{'sem'}->remove();
+    }
 
     if ($prop->{'_HUP'}) {
         $self->restart_close_hook();
```

Best regards,
Emanuele

**Comment by rhandom** [comment]
Thank you.  The patch will be in the next release.
