### ISSUE TITLE
uninitialized value in numeric eq (==) in Fork L168

### ISSUE THREAD

**Issue by oliwel** [rhandom/perl-net-server#32]
Changes made in Net::Server.:Fork Line 168 with commit 5a689da0852d550ab301f0994b8a7820bba157a9 cause a flood of errors: `Use of uninitialized value in numeric eq (==) at Net/Server/Fork.pm line 168` 

We use a unix domain "file" socket.

Our code can be found here https://github.com/openxpki/openxpki/blob/develop/core/server/OpenXPKI/Server.pm
The problem is gone after undoing the changes in the line made by above commit.

**Comment by gregoa** [comment]
Probably fixed by the PR in #33 

Also reported as https://rt.cpan.org/Public/Bug/Display.html?id=146575

**Comment by rhandom** [comment]
Thank you for your report and for those that provided the PR 33 patch.  This has been applied to the just uploaded 2.014
