### ISSUE TITLE
Unable to build using perl 5.25.10.

### ISSUE THREAD

**Issue by jomo666** [rhandom/perl-net-server#9]
Got:
```
Unimplemented: POSIX::tmpnam(): use File::Temp instead at /.../plenv/versions/5.25.10/lib/perl5/5.25.10/darwin-2level/POSIX.pm line 185.
Unimplemented: POSIX::tmpnam() at t/UNIX_test.t line 5.
BEGIN failed--compilation aborted at t/UNIX_test.t line 5.
```

**Comment by ppisar** [comment]
A proposed fix is at <https://github.com/rhandom/perl-net-server/pull/10>.

**Comment by zakame** [comment]
See also https://rt.cpan.org/Ticket/Display.html?id=105512

**Comment by abraxxa** [comment]
This affects Catalyst::Devel. Please get in touch with the Catalyst maintainers if a new module maintainer is required.

**Comment by rhandom** [comment]
New release was finally released.

**Comment by zakame** [comment]
Thanks @rhandom !

**Comment by jomo666** [comment]
Thank you! :)
